
image: gitpod/workspace-mysql:latest
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: |
      mysql -e "create database Northwind"
      mysql -u root -p Northwind < Northwind/northwind.sql
      mysql -e "show databases"
      mysql -e "show tables from Northwind"
      echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3306
    onOpen: open-preview

vscode:
  extensions:
    - cmoog.sqlnotebook
#      host: localhost
#      port: 3306
#      user: root
#      database: Northwind
#      driver: mysql
